### ISSUE TITLE
Incorrect testnet installation path for genesis.json and config.json

### ISSUE THREAD

**Issue by nujabes403** [aurora-is-near/standalone-rpc#11]
I've noticed that the installation path for genesis.json and config.json files for the testnet is incorrect.

Currently, the installation path for these files is set as https://files.deploy.aurora.dev/testnet-new-rpc/, which results in an error when trying to install them.

The correct installation path for the testnet files should be https://files.deploy.aurora.dev/testnet/.

Please update the installation path for these files so that users can install and use the testnet without any issues.

Current: Not available paths
https://files.deploy.aurora.dev/testnet-new-rpc/config.json
https://files.deploy.aurora.dev/testnet-new-rpc/genesis.json.gz

To be:
https://files.deploy.aurora.dev/testnet/config.json
https://files.deploy.aurora.dev/testnet/genesis.json.gz

**Comment by akeyder** [comment]
thank you @nujabes403, pushed to pipe-line
