### ISSUE TITLE
What are the hardware requirements for running this RPC node?

### ISSUE THREAD

**Issue by WuTao18** [aurora-is-near/standalone-rpc#4]
I would like to know the recommended hardware specifications for running an RPC node, including CPU, memory, storage, etc.

**Comment by WuTao18** [comment]
> Hey, @WuTao18. That depends on what mode you are running. If you run with `-r nearcore` then you can use the same requirements as when running regular near rpc node. You can check details [here](https://near-nodes.io/rpc/hardware-rpc). You will need to add additional 50-100 GB of storage for relayer database. If you use `-r datalake` then it's 50-100 GB of storage on SSD/nvme, any reasonable processor, 16 GB RAM.

I see, thank you for your reply.

**Comment by Karkunow** [comment]
Closing this one :) Seems to be resolved for now
